Add TLS Support
jhthorsen/mojo-redis pull request #80
Opened 2023-10-09 12:37 UTC by hazemkmammu

- Add TLS Support by accepting TLS options and passing them to Mojo::IOLoop::Client.

2023-10-09 12:41 UTC, hazemkmammu commented
@jhthorsen Hi Jan. Could you please review this change? This should add support for TLS connection to Redis. SSL/TLS is supported by Redis starting with version 6. Please let me know if you have any questions. Thanks.

2023-10-14 00:07 UTC, jhthorsen requested changes
Thanks for the contribution, but I think there's too many attributes. Also, the documentation should get some updates.

2023-10-14 00:07 UTC, jhthorsen commented on .gitignore
> +.idea/
What is this?

2023-10-14 00:07 UTC, jhthorsen commented on lib/Mojo/Redis.pm
> +has 'tls_options';
I would rather have this part of the "url", like https://docs.mojolicious.org/Mojo/Server/Daemon#listen

Example:

```
Mojo::URL->new("redis://localhost?ca=ca.pem&cert=cert.pemt&key=key.pm")
```

And "tls" can be set to true if key and cert exists.

2025-12-03 14:08 UTC, akarelas commented on lib/Mojo/Redis.pm
> +has 'tls_options';
What if someone wants only the server to certify itself, not the client.

You should allow a plain tls=1 option there I think.

2026-06-04 01:38 UTC, jhthorsen commented
Closing this in favor of #84. Sorry if that was the wrong order.

2026-06-04 01:38 UTC, closed without merging